### ISSUE TITLE
Installation fail because of stage 3 signature

### ISSUE THREAD

**Issue by truecrime** [martincmelik/Securix-Linux#103]
I tried to install Securix in VirtualBox but the installation failed when verifying stage3. I have attached a screenshot with the error.
![screenshot from 2015-02-11 21 46 18](https://cloud.githubusercontent.com/assets/5936242/6160969/fad0efd8-b237-11e4-8366-f893dde4fdeb.png)

**Comment by martincmelik** [comment]
Hi,
first: for entropy generation is better to open another console (Alt+F2) and type (anything) here. Then go back by (Alt+F1).

As you can see when downloading files from Securix, status will end with "100% DONE", but when you tried to download first ".tar.bz2" [file](https://mirror.securix.org/releases/amd64/autobuilds/20150108/hardened/stage3-amd64-hardened-20150108.tar.bz2), then it fails and all others as well.

This never happen to me. Will test it today.

**Comment by martincmelik** [comment]
OK, it seems that Gentoo developers changed "latest file" format. Quick fix (bc95c86) solved this issue.

**Comment by truecrime** [comment]
Thank you!
