### ISSUE TITLE
emerge using gpg verification in chroot.sh?

### ISSUE THREAD

**Issue by adrelanos** [martincmelik/Securix-Linux#45]
I see in `chroot.sh` you are the system to use gpg verification for package installations from Gentoo repository, right? ([Line 360](https://github.com/martincmelik/securix/blob/master/install/chroot.sh#L360))

But you are using `emerge` 6 times or so in earlier lines such as in [line 162](https://github.com/martincmelik/securix/blob/master/install/chroot.sh#L162).

So it is not using gpg verification at that point?

If my guess is right, could you fix this please?

**Comment by martincmelik** [comment]
forgot to close this
```emerge --sync``` is not used anymore
