### ISSUE TITLE
option to skip installing securix configuration files --configfiles securix|none

### ISSUE THREAD

**Issue by adrelanos** [martincmelik/Securix-Linux#59]
Securix comes with a lot derivative configuration files. Also Whonix comes with its own config files that are shipped by various packages. (See also: https://github.com/Whonix/Gentoo-Port/issues/12 / https://github.com/Whonix/Gentoo-Port/issues/13) Having both derivatives ship configuration files is very likely to cause conflicts and confusion. Also both derivatives are targeting different use cases.

For the sake of this ticket, some terminology is required. Securix has two types of configuration files:

* "static configuration files", which are located at https://github.com/martincmelik/securix/tree/master/config/securix-conf
* "dynamic configuration files", which are dynamically created by the install script depending on environment (for example, VM or not) and user settings.

So for a Whonix Gentoo Hardened port, a `--configfiles securix|none` or so parameter, environment variable or settings file would be required.

Feel free to have "`--configfiles securix`" as default. It would do the same as currently. And "`--configfiles none`" wouldn't install any of the "static configuration files". (The latter would also be interesting for users who just want to use Hardened Gentoo without extra config files, I could imagine.)

As for "dynamic configuration files", I don't think an option for not creating them is required at this point. (Even if any of them, such as /etc/resolv.conf was to clash with any settings Whonix requires, after installing the base operating system, a Whonix settings package could replace that file without conflict, because those are only touched once by the install script.)

**Comment by adrelanos** [comment]
Implemented this here:
https://github.com/martincmelik/Securix-Linux/pull/73

**Comment by martincmelik** [comment]
done
