### ISSUE TITLE
Stage3 GPG signature verification broken

### ISSUE THREAD

**Issue by adrelanos** [martincmelik/Securix-Linux#93]
As of current master https://github.com/martincmelik/Securix-Linux/blob/14e4fd445235e4bf384fd8ffb65e1c43d7bfe9ac/securix-install/install.sh#L821 Stage3 GPG signature verification is broken.

```
    # verify stage3 GPG
    f_msg info "###-### Step: Verifying Stage3 GPG signature"
    gpg ${GPG_EXTRA_OPTS} --homedir /etc/portage/gpg --verify "${STAGE3LATESTFILE##*/}.DIGESTS.asc"
```

Currently ineffective, because the exit code is unchecked.

This is an example why #60 is important.

I might provide a quick band aid fix in a pull request that fixes a few other issues of that kind.

**Comment by martincmelik** [comment]
I assume this has been addressed by your pull request and can be closed, right?

**Comment by adrelanos** [comment]
Yes.
